version: '3.8'

services:

  app:
    build: .docker/keycloak
    container_name: mykeycloak
    depends_on:
      - db
    ports:
      - "8443:8443" # for production
      - "8080:8080" # for development
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mykeycloak-db:3306/keycloak?characterEncoding=UTF-8
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KC_BOOTSTRAP_ADMIN_USERNAME: admin 
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_HTTP_ENABLED: "true" # for development
      KC_MODE: dev # for development, dont forget to change command to start in production
    command: >
      start-dev --spi-dblock-jpa-lock-wait-timeout 300
      
  db:
    build: .docker/mysql
    container_name: mykeycloak-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_EXTRA_FLAGS: "--sql-generate-invisible-primary-key=OFF"
    ports:
      - "3310:3306"
    volumes:
      - ./data/dbdata:/var/lib/mysql